# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- none
 
pool:
  vmImage: ubuntu-latest
 
stages:
- stage: Stage1
  jobs:
  - job: Stage1_Job1
    steps:
    - task: PowerShell@2
      displayName: 'Stage1-Job1-Task1'
      name: 'Stage1_Job1_Task1'
      inputs:
        targetType: 'inline'
        script: |
         Write-Host "##vso[task.setvariable variable=SASToken;isoutput=true;]TestSASTokenValue"
    -  task: PowerShell@2
       displayName: 'Stage1-Job1-Task2'
       continueOnError: true
       inputs:
          targetType: 'inline'
          script: |
           Write-Host "The value of SASToken: $(Stage1_Job1_Task1.SASToken)"
  - job: Stage1_Job2
    dependsOn: Stage1_Job1
    variables:
    - name: NewSASToken
      value: $[dependencies.Stage1_Job1.outputs['Stage1_Job1_Task1.SASToken']]
    steps:
    - task: PowerShell@2
      displayName: 'Stage1-Job2-Task1'
      inputs:
        targetType: 'inline'
        script: |
           'Write-Host "The value of SASToken is $(NewSASToken)"'
    - task: PowerShell@2
      displayName: 'Stage1-Job2-Task2'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
- stage: Stage2
  variables:
    - name: NewSASToken
      value: $[stageDependencies.Stage1.Stage1_Job1.outputs['Stage1_Job1_Task1.SASToken']]
  jobs:
  - job: Stage2_Job1
    steps:
    - task: PowerShell@2
      displayName: 'Stage2-Job1-Task1'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "The value of SASToken in Stage2: $(NewSASToken)"'
    - task: PowerShell@2
      displayName: 'Stage2-Job1-Task2'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
  - job: Stage2_Job2
    steps:
    - task: PowerShell@2
      displayName: 'Stage2-Job2-Task1'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
    - task: PowerShell@2
      displayName: 'Stage2-Job2-Task2'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'