# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      displayName: 'When ExecuteTaskBaseOnCondition is True'
      condition: eq(variables['ExecuteTaskBaseOnCondition'], 'true')
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello World"
    - task: PowerShell@2
      displayName: 'No Conditions'    
      inputs:
        targetType: 'inline'
        script: Write-Host "Hello World"