# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: 'dev'
  displayName: ' dev environment'
  

  variables:
    configuration: debug
    ExecuateTaskBasedonCodition: true

  jobs:
  - job: Job1
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      condition: eq(variables['ExecuateTaskBasedonCodition'],'true')

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: Job2
    dependsOn: Job1
    pool:
      vmImage: ubuntu-latest
    condition: succeededOrFailed()
    steps:
    
    - task: PowerShell@2
      displayName: 'Not So important Task'
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
            # Write your PowerShell commands here.
             Write-Hosts "Hello World"
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
            # Write your PowerShell commands here.
             Write-Host "Hello World"
    
